language: node_js
node_js:
  - '10'
stages:
  - name: lint and test
  - name: publish
    if: branch = master
jobs:
  include:
    - stage: lint and test
      name: eslint and prettier
      script: 
        - npm run prettier
        - npm run lint
    - script: npm run ci-test
      name: unit test
    - stage: publish
      name: npm publish
      script: 
        - npm run ci-build
        - npm run ci-publish
    - script: npm run ci-build:docs
      name: gitHub pages
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: docs
        keep_history: true
        on:
          branch: master